packages:
  - templates/*
  - docs
catalog:
  "@antfu/eslint-config": 4.4.0
  "@iconify-json/carbon": ^1.1.27
  "@iconify-json/file-icons": ^1.1.8
  "@iconify-json/logos": ^1.1.33
  "@iconify-json/material-symbols": ^1.1.66
  "@iconify-json/mdi": ^1.1.52
  "@iconify-json/ph": ^1.1.5
  "@iconify-json/twemoji": ^1.1.11
  "@iconify-json/unjs": ^1.1.0
  "@iconify-json/vscode-icons": ^1.1.25
  "@netlify/functions": ^2.4.0
  "@shikijs/markdown-it": 2.1.0
  "@shikijs/transformers": 2.1.0
  "@shikijs/vitepress-twoslash": 2.1.0
  "@types/babel__core": ^7.20.1
  "@types/fs-extra": ^9.0.13
  "@types/hast": ^3.0.3
  "@types/markdown-it": ^14.1.2
  "@types/minimist": ^1.2.5
  "@types/node": ^22.15.13
  "@types/nodemailer": ^6.4.14
  "@types/nprogress": ^0.2.3
  "@types/prompts": ^2.4.8
  "@unocss/postcss": ^0.61.0
  "@vitejs/plugin-vue": 5.2.1
  "@vitest/coverage-v8": 3.0.7
  "@vitest/ui": 3.0.7
  "@vue/repl": ^3.0.0
  "@vue/test-utils": 2.4.1
  "@vueuse/core": ^10.7.0
  atropos: ^1.0.2
  bumpp: 8.2.1
  cac: 6.7.14
  consola: ^3.2.3
  cz-conventional-changelog: ^3.3.0
  es-toolkit: ^1.9.0
  eslint: 9.21.0
  esno: 0.16.3
  execa: ^9.5.2
  filesize: ^10.1.4
  fs-extra: ^11.1.1
  gh-pages: 5.0.0
  giget: ^1.2.1
  happy-dom: 8.9.0
  hast-util-from-html: ^2.0.1
  hast-util-to-html: ^9.0.0
  hastscript: ^8.0.0
  husky: 8.0.3
  js-yaml: ^4.1.0
  kolorist: ^1.8.0
  lz-string: ^1.5.0
  markdown-it-container: ^4.0.0
  markdown-it-magic-link: ^0.0.2
  markdown-it-multimd-table: ^4.2.3
  mermaid: ^10.6.1
  minimist: ^1.2.8
  nanoid: ^5.0.4
  netlify-cli: ^17.10.2
  nodemailer: ^6.9.8
  nprogress: ^0.2.0
  ofetch: ^1.1.1
  ora: ^8.0.1
  prompts: ^2.4.2
  rehype-stringify: ^10.0.0
  remark-parse: ^11.0.0
  remark-rehype: ^11.0.0
  shiki: 2.1.0
  shiki-magic-move: ^0.3.4
  simple-git: ^3.22.0
  stylus: ^0.62.0
  tar: ^7.4.3
  taze: ^0.9.2
  ts-morph: ^21.0.1
  tsup: ^6.7.0
  typescript: 5.8.2
  ufo: ^1.3.2
  unbuild: 3.5.0
  unified: ^11.0.4
  unist-util-visit: ^5.0.0
  unocss: ^0.61.0
  unplugin-icons: ^0.17.0
  unplugin-vue-components: ^0.25.1
  unsplash-js: ^7.0.18
  v-viewer: ^3.0.11
  viewerjs: ^1.11.4
  vite: 5.4.14
  vite-plugin-dts: 2.3.0
  vite-plugin-inspect: ^0.7.42
  vitepress: ^1.6.3
  vitest: 3.0.7
  vue: 3.5.13
  vue-tsc: 1.8.22
  vue3-lazyload: ^0.3.8
