/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApiCompatibility: typeof import('./.vitepress/theme/components/ApiCompatibility.vue')['default']
    CodeEditor: typeof import('./.vitepress/theme/components/CodeEditor.vue')['default']
    Document: typeof import('./.vitepress/theme/components/Document.vue')['default']
    DownloadButton: typeof import('./.vitepress/theme/components/DownloadButton.vue')['default']
    FileTree: typeof import('./.vitepress/theme/components/FileTree.vue')['default']
    GitHubLink: typeof import('./.vitepress/theme/components/GitHubLink.vue')['default']
    'GitHubLink copy': typeof import('./.vitepress/theme/components/GitHubLink copy.vue')['default']
    GitHubStar: typeof import('./.vitepress/theme/components/GitHubStar.vue')['default']
    'GitHubStar copy': typeof import('./.vitepress/theme/components/GitHubStar copy.vue')['default']
    HeadFigure: typeof import('./.vitepress/theme/components/HeadFigure.vue')['default']
    HomePage: typeof import('./.vitepress/theme/components/HomePage.vue')['default']
    'HomePage copy': typeof import('./.vitepress/theme/components/HomePage copy.vue')['default']
    LinkGrid: typeof import('./.vitepress/theme/components/LinkGrid.vue')['default']
    LogosBashIcon: typeof import('~icons/logos/bash-icon')['default']
    LogosHtml5: typeof import('~icons/logos/html5')['default']
    LogosMarkdown: typeof import('~icons/logos/markdown')['default']
    LogosNpmIcon: typeof import('~icons/logos/npm-icon')['default']
    LogosTypescriptIcon: typeof import('~icons/logos/typescript-icon')['default']
    LogosYoutubeIcon: typeof import('~icons/logos/youtube-icon')['default']
    MaterialSymbolsDownload2: typeof import('~icons/material-symbols/download2')['default']
    MdiFileDocument: typeof import('~icons/mdi/file-document')['default']
    Mermaid: typeof import('./.vitepress/theme/components/Mermaid.vue')['default']
    NpmLink: typeof import('./.vitepress/theme/components/NpmLink.vue')['default']
    PermaLink: typeof import('./.vitepress/theme/components/PermaLink.vue')['default']
    PersonProfile: typeof import('./.vitepress/theme/components/PersonProfile.vue')['default']
    Plum: typeof import('./.vitepress/theme/components/Plum.vue')['default']
    Quote: typeof import('./.vitepress/theme/components/Quote.vue')['default']
    'Quote copy': typeof import('./.vitepress/theme/components/Quote copy.vue')['default']
    ShikiMagicMove: typeof import('./.vitepress/theme/components/ShikiMagicMove.vue')['default']
    SvgWrapper: typeof import('./.vitepress/theme/components/SvgWrapper.vue')['default']
    TableDemo: typeof import('./.vitepress/theme/components/TableDemo.vue')['default']
    Tweet: typeof import('./.vitepress/theme/components/Tweet.vue')['default']
    VImg: typeof import('./.vitepress/theme/components/VImg.vue')['default']
    VPSwitch: typeof import('./.vitepress/theme/components/VPSwitch.vue')['default']
    VPSwitchAppearance: typeof import('./.vitepress/theme/components/VPSwitchAppearance.vue')['default']
    YouTube: typeof import('./.vitepress/theme/components/YouTube.vue')['default']
  }
}
